" -----------------------------------------------------------------------------
"
" ~/.vimrc
"
" This file is a part of the workspace setup
" https://github.com/sfi0zy/workspace-setup/tree/elementary-os-7
"
" -----------------------------------------------------------------------------


" start the pathogen

execute pathogen#infect()
call pathogen#helptags()

" open the NERDTree automatically when the vim starts up

autocmd vimenter * NERDTree
let NERDTreeShowHidden = 1

" set the current directory

set autochdir

" activate the wildmenu

set wildmenu

" activate the filetype plugin for the future commands

filetype plugin on


" -----------------------------------------------------------------------------
" Visual settings
" -----------------------------------------------------------------------------

" apply the colorscheme
" https://github.com/sfi0zy/atlantic-dark.vim

colorscheme atlantic-dark
let g:airline_theme='term'

" show the line numbers by default

set nu

" show 5 lines before/after the cursor if it's possible

set scrolloff=5

" set the color for the vertical lines (indentations)

let g:indentLine_color_term = 236

" fill the columns 80+
" (`join` is not necessary, we're saving it here for the future tests)

highlight ColorColumn ctermbg=232 guibg=#060606
let &colorcolumn="80,".join(range(81,999),",")

" highlight the search results

set hlsearch
set incsearch

" highlight the parens

set showmatch


" -----------------------------------------------------------------------------
" Text editing
" -----------------------------------------------------------------------------

" set the fallback settings for the tabs and the line endings
" (editorconfig will rewrite all these settings for the particular projects)

set tabstop=4
set shiftwidth=4
set expandtab
autocmd BufWritePre * set ff=unix
autocmd BufWritePre * %s/\s\+$//e

" disable the auto comments

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o


" -----------------------------------------------------------------------------
" Syntax highlighting
" -----------------------------------------------------------------------------

" enable the syntax highlighting by default

syntax on

" disable the highlighting on the long lines
" (improves the performance, can cause wrong highlighting in the next lines)

set synmaxcol=120

" disable that crazy syntax highlighting for the json and markdown files

autocmd FileType json     setlocal syntax=off nospell
autocmd FileType markdown setlocal syntax=off nospell

" highlight the ES6 template strings
" (they're not highlighting properly by default)

hi link javaScriptTemplateDelim  String
hi link javaScriptTemplateVar    Text
hi link javaScriptTemplateString String

" now hyphens are the part of the identifiers (it helps with the highlighting)

au! FileType css,less,html setl iskeyword+=-


" -----------------------------------------------------------------------------
" Code completion
" -----------------------------------------------------------------------------

" set the emmet leader key

let g:user_emmet_leader_key = '<C-Z>'

" Set the default quote char for the emmet

let g:user_emmet_settings = {
    \  'html' : {
    \    'quote_char': "'",
    \  },
    \}


" -----------------------------------------------------------------------------
" Linters
" -----------------------------------------------------------------------------

" choose the linters

let g:ale_linters = {
\   'sh': ['shellcheck'],
\   'css': ['stylelint'],
\   'less': ['stylelint'],
\   'sass': ['stylelint'],
\   'javascript': ['eslint'],
\   'typescript': ['eslint'],
\   'typescriptreact': ['eslint'],
\}

" choose when to lint

let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1

" more visual settings for the ALE

let g:ale_linters_explicit = 1
let g:ale_echo_msg_error_str = 'error'
let g:ale_echo_msg_warning_str = 'warning'
let g:ale_echo_msg_info_str = 'info'
let g:ale_echo_msg_log_str = 'log'
let g:ale_echo_msg_format = '[%severity%][%linter%] %s [%code%]'
let g:ale_sign_column_always = 1
let g:ale_set_highlights = 0
