" start pathogen

execute pathogen#infect()
call pathogen#helptags()

function FindSessionDirectory() abort
    if len(argv()) > 0
        return fnamemodify(argv()[0], ':p:h')
    endif
    return getcwd()
endfunction!

" set fallback settings for the tabs and line endings (before editorconfig)

set tabstop=4
set shiftwidth=4
set expandtab
autocmd BufWritePre * set ff=unix
autocmd BufWritePre * %s/\s\+$//e

" set color for the vertical lines (indentations)

let g:indentLine_color_term = 236

" show the line numbers by default

set nu

" open the NERDTree automatically when the vim starts up

autocmd vimenter * NERDTree
let NERDTreeShowHidden = 1

" set the current directory to skip %:h/ in the commands

:set autochdir

" enable syntax highlighting by default

syntax on

" disable highlighting on the long lines (improves performance, can cause
" wrong highlighting in the next lines)

set synmaxcol=120

" apply the colorscheme

colorscheme atlantic-dark
let g:airline_theme='term'

" fill the columns 80+ (saving join here for future tests)

highlight ColorColumn ctermbg=232 guibg=#060606
let &colorcolumn="80,".join(range(81,999),",")

" highlight the search results

set hlsearch
set incsearch

" highlight the parens

set showmatch

" highlight the ES6 template strings

hi link javaScriptTemplateDelim  String
hi link javaScriptTemplateVar    Text
hi link javaScriptTemplateString String

" now hyphens are the part of the identifiers

au! FileType css,less,html setl iskeyword+=-

" enable the code completion

filetype plugin on
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html       set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css        set omnifunc=csscomplete#CompleteCSS

" activate omni on Tab

function! TabOrComplete()
    if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
        return "\<C-X>\<C-O>"
    else
        return "\<Tab>"
    endif
endfunction

inoremap <Tab> <C-R>=TabOrComplete()<CR>

" activate the wildmenu

set wildmenu

" change the default trigger key for the emmet

let g:user_emmet_leader_key = '<C-Z>'

" disable the auto comments

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" disable that crazy syntax highlighting for the json and markdown files

autocmd FileType json     setlocal syntax=off nospell
autocmd FileType markdown setlocal syntax=off nospell

" settings for ALE

let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1

let g:ale_linters = {
\   'css': ['stylelint'],
\   'less': ['stylelint'],
\   'javascript': ['eslint'],
\}
let g:ale_linters_explicit = 1

let g:ale_echo_msg_error_str = 'error'
let g:ale_echo_msg_warning_str = 'warning'
let g:ale_echo_msg_info_str = 'info'
let g:ale_echo_msg_log_str = 'log'
let g:ale_echo_msg_format = '[%severity%][%linter%] %s [%code%]'

let g:ale_sign_column_always = 1
let g:ale_set_highlights = 0
